[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdb = "0.3.1"
tokio = { version = "1", features = ["full"] }
bytes = "1.1.0"

[features]
default = ["fdb/fdb-7_1"]
